deliveries initial logic
Mindaho/KTU-Mom-s-spaghetti pull request #7
Opened 2020-12-08 21:19 UTC by Mindaho

2020-12-08 21:19 UTC, Mindaho commented
Not ready.

2020-12-09 15:48 UTC, AivarasTaroza requested changes
Also, in CreateOrder, the request with the comment is ignored.

2020-12-09 15:48 UTC, AivarasTaroza commented on models/delivery.go
> +	DeliveryCompleteTime  time.Time `json:"deliveryCompleteTime"`
Returns "deliveryCompleteTime": "0001-01-01T00:00:00Z" instead of null

2020-12-09 15:48 UTC, AivarasTaroza commented on models/delivery.go
> +
Should check delivery status

2020-12-09 15:48 UTC, AivarasTaroza commented on models/delivery.go
> +	OrderID               uint      `json:"-"`
When getting the list of all deliveries it would be useful to have the orderId

2020-12-09 15:48 UTC, AivarasTaroza commented on controllers/delivery.go
> +//TODO AddDeliveryReview
I'll handle the reviews

2020-12-09 16:28 UTC, AivarasTaroza commented
Oh, and order_dish still doesn't have a copy of profit_margin

2020-12-09 16:47 UTC, AivarasTaroza commented on models/order.go
> -	StatusDelivering OrderStatus = "delivering"
Not removed in migration

2020-12-09 16:48 UTC, AivarasTaroza commented on models/order.go
> +	StatusAccepted  OrderStatus = "accepted"
"accepted" is not in the report.

2020-12-10 15:56 UTC, AivarasTaroza commented on controllers/delivery.go
> +//TODO AddDeliveryReview
Done on another branch

2020-12-10 15:59 UTC, AivarasTaroza commented on models/order.go
> -	StatusDelivering OrderStatus = "delivering"
You should fix this in a new migration file so it would run after the one in the other branch.

2020-12-11 08:47 UTC, merged